name: rugpt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python>=3.8,<3.9
  - pip
  - pytorch>=1.7.1
  - tensorboard
  - pip:
    - transformers==3.5.1
    - fastai>=2
    - tendo
    - fastapi
    - uvicorn
    - natsort
    - ipywidgets
    - triton==0.2.3
#    - torch-blocksparse
